from enum import StrEnum


class TenantType(StrEnum):
    HOTEL = "HOTEL"
    RESORT = "RESORT"
    AIRBNB_OPERATOR = "AIRBNB_OPERATOR"
    AIRPORT_LOUNGE = "AIRPORT_LOUNGE"
    HOSPITALITY_GROUP = "HOSPITALITY_GROUP"


class UserRole(StrEnum):
    PLATFORM_SUPER_ADMIN = "PLATFORM_SUPER_ADMIN"
    TENANT_ADMIN = "TENANT_ADMIN"
    MANAGER = "MANAGER"
    RECEPTIONIST = "RECEPTIONIST"
    ACCOUNTANT = "ACCOUNTANT"
    OPERATIONS_STAFF = "OPERATIONS_STAFF"


class RoomStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    OCCUPIED = "OCCUPIED"
    MAINTENANCE = "MAINTENANCE"
    OUT_OF_SERVICE = "OUT_OF_SERVICE"


class ReservationStatus(StrEnum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    CHECKED_IN = "CHECKED_IN"
    CHECKED_OUT = "CHECKED_OUT"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class AnalyticsEventType(StrEnum):
    RESERVATION_CREATED = "RESERVATION_CREATED"
    CHECK_IN = "CHECK_IN"
    CHECK_OUT = "CHECK_OUT"
    PAYMENT_POSTED = "PAYMENT_POSTED"
    ROOM_MAINTENANCE = "ROOM_MAINTENANCE"
